spring.application.name=chuck

server.port=9008

# \uD0C0\uC784\uB9AC\uD504
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# config properties
spring.config.import=config.properties

#chuck server config(?? ??)
chuck.server.url=https://localhost:8080 