spring.application.name=chuck

server.port=9008
# SSL \uC124\uC815
server.ssl.enabled=true
server.ssl.key-store=src/main/resources/config/keystore.jks
server.ssl.key-store-password=cc0914!@

security.require-ssl=true

# \uD0C0\uC784\uB9AC\uD504
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# api key
# \uCC9C\uBB38\uD559 \uD2B9\uC77C \uC81C\uACF5 service key
data.api.encoding=IWJek59zz%2B4jWdN26QqLDylht8VcyZ4C89clHK53%2F58jkUaiTvxNfTniSPNcwE%2FpHHVMqh46jGOcGTMzuCvRoQ%3D%3D
data.api.decoding=IWJek59zz+4jWdN26QqLDylht8VcyZ4C89clHK53/58jkUaiTvxNfTniSPNcwE/pHHVMqh46jGOcGTMzuCvRoQ==

#chuck server config(API \uC11C\uBC84)
chuck.server.url=https://192.168.0.106:28444/emp/login

## json \uBAA8\uC158
#spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/config/