# api key
# \uCC9C\uBB38\uD559 \uD2B9\uC77C \uC81C\uACF5 service key
data.api.encoding=IWJek59zz%2B4jWdN26QqLDylht8VcyZ4C89clHK53%2F58jkUaiTvxNfTniSPNcwE%2FpHHVMqh46jGOcGTMzuCvRoQ%3D%3D
data.api.decoding=IWJek59zz+4jWdN26QqLDylht8VcyZ4C89clHK53/58jkUaiTvxNfTniSPNcwE/pHHVMqh46jGOcGTMzuCvRoQ==